package store

import (
	"time"

	"github.com/neartap/server/internal/models"
)

// mockTaps is used when no Firebase credentials are present (demo mode)
var mockTaps = []models.Tap{
	{
		ID:                  "1",
		Name:                "BBMP Community Tap – MG Road",
		Address:             "Near MG Road Flyover, Halasuru, Bengaluru 560008",
		Lat:                 12.9758,
		Lng:                 77.6095,
		Hours:               "24/7",
		IsOpen:              true,
		IsFree:              true,
		PaymentMethods:      []string{},
		IsVerified:          true,
		IsAccessible:        true,
		WaterQuality:        "RO Purified",
		Description:         "BBMP-maintained RO kiosk near MG Road flyover. Digital QR payment available. Very high footfall.",
		LastReportedWorking: time.Now().AddDate(0, 0, -1),
		AddedBy:             models.UserRef{UID: "bbmp-official", Name: "BBMP Ward 68"},
		Photos:              []string{"https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400"},
		Confirmations:       9,
		Issues:              []string{},
		CreatedAt:           time.Now().AddDate(0, -3, 0),
		UpdatedAt:           time.Now().AddDate(0, 0, -1),
	},
	{
		ID:                  "2",
		Name:                "Cubbon Park Drinking Fountain",
		Address:             "Near Bandstand, Cubbon Park, Bengaluru 560001",
		Lat:                 12.9763,
		Lng:                 77.5929,
		Hours:               "06:00 – 20:00",
		IsOpen:              true,
		IsFree:              true,
		PaymentMethods:      []string{},
		IsVerified:          true,
		IsAccessible:        true,
		WaterQuality:        "Municipal",
		Description:         "Heritage stone fountain near the Bandstand inside Cubbon Park. Maintained by BBMP Horticulture dept.",
		LastReportedWorking: time.Now().AddDate(0, 0, -2),
		AddedBy:             models.UserRef{UID: "user1", Name: "Arjun Nair"},
		Photos:              []string{"https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400"},
		Confirmations:       6,
		Issues:              []string{},
		CreatedAt:           time.Now().AddDate(0, -2, 0),
		UpdatedAt:           time.Now().AddDate(0, 0, -2),
	},
	{
		ID:                  "3",
		Name:                "Vidhana Soudha Water Kiosk",
		Address:             "Ambedkar Veedhi, Vidhana Soudha, Bengaluru 560001",
		Lat:                 12.9794,
		Lng:                 77.5913,
		Hours:               "08:00 – 18:00",
		IsOpen:              true,
		IsFree:              true,
		PaymentMethods:      []string{},
		IsVerified:          true,
		IsAccessible:        true,
		WaterQuality:        "RO Purified",
		Description:         "Government-run BWSSB kiosk outside Vidhana Soudha. Clean, well-maintained, tested weekly.",
		LastReportedWorking: time.Now().AddDate(0, 0, -1),
		AddedBy:             models.UserRef{UID: "bwssb-official", Name: "BWSSB Zone 3"},
		Photos:              []string{"https://images.unsplash.com/photo-1501854140801-50d01698950b?w=400"},
		Confirmations:       12,
		Issues:              []string{},
		CreatedAt:           time.Now().AddDate(0, -1, 0),
		UpdatedAt:           time.Now().AddDate(0, 0, -1),
	},
	{
		ID:                  "4",
		Name:                "Ward Office Tap – Indiranagar",
		Address:             "Opp. Ward 68 Office, 100 Feet Road, Indiranagar, Bengaluru 560038",
		Lat:                 12.9784,
		Lng:                 77.6408,
		Hours:               "06:00 – 22:00",
		IsOpen:              true,
		IsFree:              true,
		PaymentMethods:      []string{},
		IsVerified:          true,
		IsAccessible:        false,
		WaterQuality:        "Filtered",
		Description:         "BBMP ward tap opposite the ward office. Tested water, open long hours. No ramp.",
		LastReportedWorking: time.Now().AddDate(0, 0, -2),
		AddedBy:             models.UserRef{UID: "user2", Name: "Meera Krishnan"},
		Photos:              []string{},
		Confirmations:       5,
		Issues:              []string{},
		CreatedAt:           time.Now().AddDate(0, -4, 0),
		UpdatedAt:           time.Now().AddDate(0, 0, -2),
	},
	{
		ID:                  "5",
		Name:                "HAL Community Water Point",
		Address:             "Near HAL Old Airport Road, Domlur, Bengaluru 560071",
		Lat:                 12.9611,
		Lng:                 77.6387,
		Hours:               "05:30 – 23:00",
		IsOpen:              true,
		IsFree:              false,
		PaymentMethods:      []string{"coin", "upi"},
		IsVerified:          false,
		IsAccessible:        true,
		WaterQuality:        "RO Purified",
		Description:         "BWSSB digital kiosk near HAL Old Airport Rd. ₹5 for 20L via QR scan or prepaid card.",
		LastReportedWorking: time.Now().AddDate(0, 0, -3),
		AddedBy:             models.UserRef{UID: "user3", Name: "Vikram Rao"},
		Photos:              []string{},
		Confirmations:       2,
		Issues:              []string{"Card reader sometimes offline"},
		CreatedAt:           time.Now().AddDate(0, -6, 0),
		UpdatedAt:           time.Now().AddDate(0, 0, -3),
	},
	{
		ID:                  "6",
		Name:                "Koramangala BDA Park Tap",
		Address:             "BDA Complex, 5th Block, Koramangala, Bengaluru 560095",
		Lat:                 12.9352,
		Lng:                 77.6245,
		Hours:               "06:00 – 21:00",
		IsOpen:              true,
		IsFree:              true,
		PaymentMethods:      []string{},
		IsVerified:          true,
		IsAccessible:        true,
		WaterQuality:        "RO Purified",
		Description:         "Inside BDA park, Koramangala 5th Block. Popular with joggers and cyclists. BWSSB-maintained.",
		LastReportedWorking: time.Now().AddDate(0, 0, -1),
		AddedBy:             models.UserRef{UID: "user4", Name: "Pooja Reddy"},
		Photos:              []string{"https://images.unsplash.com/photo-1565117154741-2a3e3ad5c2e4?w=400"},
		Confirmations:       7,
		Issues:              []string{},
		CreatedAt:           time.Now().AddDate(0, -2, 0),
		UpdatedAt:           time.Now().AddDate(0, 0, -1),
	},
	{
		ID:                  "7",
		Name:                "Govt School RO Tap – Koramangala",
		Address:             "GHPS Koramangala, 4th Block, Bengaluru 560034",
		Lat:                 12.9298,
		Lng:                 77.6171,
		Hours:               "09:00 – 17:00",
		IsOpen:              false,
		IsFree:              true,
		PaymentMethods:      []string{},
		IsVerified:          false,
		IsAccessible:        false,
		WaterQuality:        "RO Purified",
		Description:         "RO tap inside GHPS school compound. Open on school days only. Weekends closed.",
		LastReportedWorking: time.Now().AddDate(0, 0, -3),
		AddedBy:             models.UserRef{UID: "user5", Name: "Suresh Babu"},
		Photos:              []string{},
		Confirmations:       2,
		Issues:              []string{},
		CreatedAt:           time.Now().AddDate(0, -3, 0),
		UpdatedAt:           time.Now().AddDate(0, 0, -3),
	},
	{
		ID:                  "8",
		Name:                "Jayanagar 4th Block Water Kiosk",
		Address:             "Near Jayanagar Shopping Complex, 4th Block, Bengaluru 560011",
		Lat:                 12.9250,
		Lng:                 77.5938,
		Hours:               "06:00 – 22:00",
		IsOpen:              true,
		IsFree:              true,
		PaymentMethods:      []string{},
		IsVerified:          true,
		IsAccessible:        true,
		WaterQuality:        "RO Purified",
		Description:         "Well-maintained BWSSB kiosk near the iconic Jayanagar shopping complex. Always busy.",
		LastReportedWorking: time.Now().AddDate(0, 0, -1),
		AddedBy:             models.UserRef{UID: "bwssb-official", Name: "BWSSB Zone 4"},
		Photos:              []string{"https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400"},
		Confirmations:       11,
		Issues:              []string{},
		CreatedAt:           time.Now().AddDate(0, -4, 0),
		UpdatedAt:           time.Now().AddDate(0, 0, -1),
	},
	{
		ID:                  "9",
		Name:                "Rajajinagar BBMP Water ATM",
		Address:             "Near Rajajinagar Metro Station, Bengaluru 560010",
		Lat:                 12.9917,
		Lng:                 77.5530,
		Hours:               "05:30 – 23:30",
		IsOpen:              true,
		IsFree:              false,
		PaymentMethods:      []string{"coin", "upi"},
		IsVerified:          true,
		IsAccessible:        true,
		WaterQuality:        "RO Purified",
		Description:         "High-traffic BWSSB digital kiosk beside Rajajinagar Purple Line Metro. ₹5 per 20L.",
		LastReportedWorking: time.Now().AddDate(0, 0, -1),
		AddedBy:             models.UserRef{UID: "user6", Name: "Nagaraj Patil"},
		Photos:              []string{},
		Confirmations:       4,
		Issues:              []string{},
		CreatedAt:           time.Now().AddDate(0, -2, 0),
		UpdatedAt:           time.Now().AddDate(0, 0, -1),
	},
	{
		ID:                  "10",
		Name:                "Basavanagudi Park Water Point",
		Address:             "Bull Temple Road, Near Gandhi Bazaar, Basavanagudi, Bengaluru 560004",
		Lat:                 12.9430,
		Lng:                 77.5707,
		Hours:               "06:00 – 20:00",
		IsOpen:              true,
		IsFree:              true,
		PaymentMethods:      []string{},
		IsVerified:          true,
		IsAccessible:        false,
		WaterQuality:        "Municipal",
		Description:         "Old municipal tap near Gandhi Bazaar, used by local vendors and residents for decades.",
		LastReportedWorking: time.Now().AddDate(0, 0, -2),
		AddedBy:             models.UserRef{UID: "user7", Name: "Lakshmi Devi"},
		Photos:              []string{},
		Confirmations:       5,
		Issues:              []string{"Sometimes muddy after rain"},
		CreatedAt:           time.Now().AddDate(0, -3, 0),
		UpdatedAt:           time.Now().AddDate(0, 0, -2),
	},
	{
		ID:                  "11",
		Name:                "Temple Trust Water Point – Whitefield",
		Address:             "Shree Ganapathi Temple, ITPL Main Road, Whitefield, Bengaluru 560066",
		Lat:                 12.9836,
		Lng:                 77.7479,
		Hours:               "07:00 – 21:00",
		IsOpen:              true,
		IsFree:              true,
		PaymentMethods:      []string{},
		IsVerified:          false,
		IsAccessible:        false,
		WaterQuality:        "Filtered",
		Description:         "Temple trust-run water point on ITPL Main Road. Free for all. Crowded during peak hours.",
		LastReportedWorking: time.Now().AddDate(0, 0, -4),
		AddedBy:             models.UserRef{UID: "user8", Name: "Ranjit Singh"},
		Photos:              []string{},
		Confirmations:       1,
		Issues:              []string{"Queue likely during rush hour"},
		CreatedAt:           time.Now().AddDate(0, -1, 0),
		UpdatedAt:           time.Now().AddDate(0, 0, -4),
	},
	{
		ID:                  "12",
		Name:                "Electronic City Phase 1 Water Kiosk",
		Address:             "BBMP Ground, Phase 1, Electronic City, Bengaluru 560100",
		Lat:                 12.8458,
		Lng:                 77.6759,
		Hours:               "24/7",
		IsOpen:              true,
		IsFree:              false,
		PaymentMethods:      []string{"coin", "upi"},
		IsVerified:          true,
		IsAccessible:        true,
		WaterQuality:        "RO Purified",
		Description:         "Round-the-clock BWSSB kiosk near IT corridor. Used heavily by night-shift workers.",
		LastReportedWorking: time.Now().AddDate(0, 0, -1),
		AddedBy:             models.UserRef{UID: "bwssb-official", Name: "BWSSB Zone 7"},
		Photos:              []string{},
		Confirmations:       8,
		Issues:              []string{},
		CreatedAt:           time.Now().AddDate(0, -5, 0),
		UpdatedAt:           time.Now().AddDate(0, 0, -1),
	},
	{
		ID:                  "13",
		Name:                "Yelahanka New Town Community Tap",
		Address:             "Near Yelahanka Bus Stand, Yelahanka, Bengaluru 560064",
		Lat:                 13.1004,
		Lng:                 77.5963,
		Hours:               "06:00 – 22:00",
		IsOpen:              true,
		IsFree:              true,
		PaymentMethods:      []string{},
		IsVerified:          false,
		IsAccessible:        true,
		WaterQuality:        "Filtered",
		Description:         "Located near the main bus stand, this BBMP tap serves passengers and daily commuters.",
		LastReportedWorking: time.Now().AddDate(0, 0, -5),
		AddedBy:             models.UserRef{UID: "user9", Name: "Anand Kumar"},
		Photos:              []string{},
		Confirmations:       2,
		Issues:              []string{},
		CreatedAt:           time.Now().AddDate(0, -2, 0),
		UpdatedAt:           time.Now().AddDate(0, 0, -5),
	},
	{
		ID:                  "14",
		Name:                "Govt School RO Tap – Shivajinagar",
		Address:             "GHPS Shivajinagar, Bengaluru 560051",
		Lat:                 12.9857,
		Lng:                 77.6012,
		Hours:               "09:00 – 17:00",
		IsOpen:              false,
		IsFree:              true,
		PaymentMethods:      []string{},
		IsVerified:          false,
		IsAccessible:        false,
		WaterQuality:        "RO Purified",
		Description:         "School compound RO tap. Open weekdays only during school hours.",
		LastReportedWorking: time.Now().AddDate(0, 0, -3),
		AddedBy:             models.UserRef{UID: "user10", Name: "Divya Prakash"},
		Photos:              []string{},
		Confirmations:       2,
		Issues:              []string{},
		CreatedAt:           time.Now().AddDate(0, -3, 0),
		UpdatedAt:           time.Now().AddDate(0, 0, -3),
	},
	{
		ID:                  "15",
		Name:                "Malleshwaram 18th Cross Tap",
		Address:             "18th Cross, Margosa Road, Malleshwaram, Bengaluru 560003",
		Lat:                 13.0036,
		Lng:                 77.5703,
		Hours:               "06:00 – 20:00",
		IsOpen:              true,
		IsFree:              true,
		PaymentMethods:      []string{},
		IsVerified:          true,
		IsAccessible:        false,
		WaterQuality:        "Municipal",
		Description:         "Classic municipal tap on Margosa Road. Popular with morning walkers at nearby ground.",
		LastReportedWorking: time.Now().AddDate(0, 0, -1),
		AddedBy:             models.UserRef{UID: "user11", Name: "Savitha Rao"},
		Photos:              []string{},
		Confirmations:       4,
		Issues:              []string{},
		CreatedAt:           time.Now().AddDate(0, -4, 0),
		UpdatedAt:           time.Now().AddDate(0, 0, -1),
	},
}
